version: '3.5'

networks:
  backend:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./projects:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      - php-7.3
      - php-7.4
      - mysql-8
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  mysql-8:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    container_name: mysql-8
    restart: unless-stopped
    volumes:
      - ./mysql-8/data:/var/lib/mysql
      - ./mysql-8/conf.d:/etc/mysql/conf.d
      - ./mysql-8/logs:/var/log/mysql/
      - ./mysql-8/dump:/dump
    ports:
      - "${MYSQL_8_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  pg:
    image: postgres:11-alpine
    container_name: pg
    volumes:
      - ./pg-11/:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${PGSQL_ROOT_USER}
        POSTGRES_PASSWORD: ${PGSQL_ROOT_PASSWORD}
        POSTGRES_DB: ${PGSQL_DATABASE}
    ports: 
        - "${PGSQL_PORT}"
    networks:
      - backend

  php-7.3:
    build:
      context: ./php-workspace/7.3
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    container_name: php-7.3
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./projects:/var/www
      - ./php-ini/7.3/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9003:9000"
    networks:
      - backend
  php-7.4:
    build:
      context: ./php-workspace/7.4
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    container_name: php-7.4
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./projects:/var/www
      - ./php-ini/7.4/php.ini:/usr/local/etc/php/php.ini

    ports:
      - "9004:9000"
    networks:
      - backend

